version: 2.1

jobs:
  build: # job name
    docker: # executor type
      - image: cimg/base:current # Docker image that installs Docker and has Git,
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Install dependencies
          command: echo "No need to install anything. \n Just build and push the Docker image."
      - run:
          name: Build and push Docker image
          command: |
            echo "Inside the Build and push Docker image step"
            docker --version # print the version for logging
            docker-compose -f docker-compose-build.yaml build --parallel
            docker tag reverseproxy huynguyen2333/reverseproxy:v5
            docker tag udagram-api-user huynguyen2333/udagram-api-user:v5
            docker tag udagram-api-feed huynguyen2333/udagram-api-feed:v5
            docker tag udagram-frontend huynguyen2333/udagram-frontend:v5
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push huynguyen2333/reverseproxy:v5
            docker push huynguyen2333/udagram-api-user:v5
            docker push huynguyen2333/udagram-api-feed:v5
            docker push huynguyen2333/udagram-frontend:v5